services:
  - type: web
    name: hop_fr_angular
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/hop_fr_angular/server/main.server.mjs
    envVars:
      - key: NODE_ENV
        value: production
    repo: https://github.com/hopOasis/hop_fr_angular
    branch: main
    autoDeployTrigger: commit
    resources:
      cpu: 0.25
      memory: 512MB
