services:
  - type: web
    name: hop_fr_angular
    env: node
    buildCommand: npm run build:ssr
    startCommand: npm run serve:ssr
    envVars:
      - key: NODE_ENV
        value: production
    resources:
      cpu: 0.25
      memory: 512MB